# Production Environment Configuration
Environment: prod
FirebaseProjectId: your-production-firebase-project

# Resource Configuration
MemorySize: 2048
Timeout: 30

# Monitoring
LogRetentionDays: 30
EnableXRayTracing: true

# DynamoDB
PointInTimeRecovery: true
EnableBackup: true

# CORS Configuration  
CorsOrigins:
  - "https://yourdomain.com"
  - "https://www.yourdomain.com"

# Tags
Tags:
  Environment: prod
  Project: BlogAPI
  CostCenter: Production
  Backup: Required