
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
  storybook:
    build: .
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm storybook