
services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      NODE_ENV: development
    command: pnpm exec next dev -H 0.0.0.0 -p 3000
  storybook:
    build: .
    ports:
      - '6006:6006'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    command: pnpm storybook