services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      # File watching in containers on macOS/Windows
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    command: pnpm exec next dev -H 0.0.0.0 -p 3000
    volumes:
      # Bind-mount source code excluding node_modules
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  storybook:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "6006:6006"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    command: pnpm storybook
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
