version: '3.8'
services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - APP_ENVIRONMENT=development
      - APP_DEBUG=true
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

